# Generated by Django 5.1.4 on 2025-01-10 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Parenthood', '0001_initial'),
        ('Person', '0003_alter_person_files_alter_person_jobs'),
        ('Relationship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parenthoods', models.ManyToManyField(blank=True, related_name='trees', to='Parenthood.parenthood')),
                ('people', models.ManyToManyField(blank=True, related_name='trees', to='Person.person')),
                ('relationships', models.ManyToManyField(blank=True, related_name='trees', to='Relationship.relationship')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Person.person')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='Tree.tree')),
            ],
        ),
    ]
