# Generated by Django 5.1.2 on 2025-01-22 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parenthood', '0001_initial'),
        ('Person', '0003_alter_job_from_date_alter_job_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parenthood',
            name='adoption_father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adoption_father_parenthoods', to='Person.person'),
        ),
        migrations.AlterField(
            model_name='parenthood',
            name='adoption_mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adoption_mother_parenthoods', to='Person.person'),
        ),
        migrations.AlterField(
            model_name='parenthood',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_parenthoods', to='Person.person'),
        ),
        migrations.AlterField(
            model_name='parenthood',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_parenthoods', to='Person.person'),
        ),
    ]
