# Generated by Django 5.1.4 on 2025-01-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='untill_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='Person.fileinfo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='jobs',
            field=models.ManyToManyField(blank=True, null=True, to='Person.job'),
        ),
        migrations.AlterField(
            model_name='surname',
            name='untill',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
