# Generated by Django 5.1.2 on 2025-01-20 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='birth', to='Person.eventinlife'),
        ),
        migrations.AlterField(
            model_name='person',
            name='death',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death', to='Person.eventinlife'),
        ),
    ]
