# Generated by Django 5.1.4 on 2025-01-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0002_alter_job_untill_date_alter_person_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='files',
            field=models.ManyToManyField(blank=True, to='Person.fileinfo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='jobs',
            field=models.ManyToManyField(blank=True, to='Person.job'),
        ),
    ]
