# Generated by Django 5.1.2 on 2025-01-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0002_alter_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='from_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
