# Generated by Django 5.1.2 on 2025-01-20 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0002_alter_person_birth_alter_person_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth', to='Person.eventinlife'),
        ),
    ]
