# Generated by Django 5.1.2 on 2025-01-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0003_alter_person_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinlife',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventinlife',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
